In [1]:
from gen_cluster_lef_def import Design
import pandas as pd

In [2]:
threshold = 0.005
util = 0.9
run_dir = '/home/fetzfs_projects/MacroPlacement/flow_scripts_run/MacroPlacement/Flows/NanGate45/ariane133/run/blob_test'
design = 'ariane'
blob_dir="/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement"
output_dir = f"{blob_dir}/blob_runs/{design}_{threshold}_{util}"

In [3]:
print("Threshold: ", threshold)
print("Util: ", util)
print("Run dir: ", run_dir)
print("Design: ", design)
print("Output dir: ", output_dir)

print("Generating cluster lef and def")

node_file = f"{run_dir}/{design}_nodes.csv"
edge_file = f"{run_dir}/{design}_edges.csv"
input_def = f"{run_dir}/{design}_placed.def"
input_macro_csv = f"{run_dir}/{design}_macro.csv"
input_lef = f"{run_dir}/28nm_12T.lef"
hgr_file = f"{run_dir}/{design}.hgr"
tech = 'ng45'

if tech == 'ng45':
    dbu = 2000
    pin_layer = 'metal1'
else:
    dbu = 1000
    pin_layer = 'M1'

design_db = Design(design, edge_file, node_file, dbu = dbu, cluster_type = 'Leiden', 
              input_def = input_def, hgr_file=hgr_file, input_lef = input_lef,
              output_dir = output_dir, cluster_macro = False,
              macro_csv = input_macro_csv)

design_db(threshold, util, pin_layer)

Threshold:  0.005
Util:  0.9
Run dir:  /home/fetzfs_projects/MacroPlacement/flow_scripts_run/MacroPlacement/Flows/NanGate45/ariane133/run/blob_test
Design:  ariane
Output dir:  /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/blob_runs/ariane_0.005_0.9
Generating cluster lef and def
Time taken for clustering: 20.71255874633789 seconds
Std cell height:1.4
Time taken to read hgr: 1.5262348651885986
Starting hierarchy clustering

100%|██████████| 391/391 [00:19<00:00, 20.55it/s]

Time taken for hierarchy clustering: 19.030428886413574
Time taken for removing parallel nets: 0.7239513397216797

In [4]:
inst_name = 'i_cache_subsystem/i_nbdcache/sram_block[4].tag_sram/macro_mem[2].i_ram'
inst = design_db.instMap[inst_name]
cluster = design_db.clusters[0].cClusters[14]
for inst in cluster.insts:
    print(inst.name)

i_cache_subsystem/i_nbdcache/i_tag_cmp/g19354
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18809
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18726
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18727
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18831
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18728
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18795
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18741
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18750
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19206
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19382
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19365
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18761
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19188
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18722
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19220
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19218
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19371
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18779
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18833
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18792
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18751
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18763
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19274
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19236
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19205
i_cache_subsystem/i_nbdcache/i_tag_cmp/FE_OCPC12549_n_174
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18855
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19475
i_cache_subsystem/i_nbdcache/i_tag_cmp/FE_OCPC12284_n_196
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19141
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19280
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19474
i_cache_subsystem/i_nbdcache/i_tag_cmp/FE_RC_500_0
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19262
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19483
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19252
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19149
i_cache_subsystem/i_nbdcache/i_tag_cmp/FE_RC_4628_0
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19234
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19296
i_cache_subsystem/i_nbdcache/i_tag_cmp/FE_RC_4732_0
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19153
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19299
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18682
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19241
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19164
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19310
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19321
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19322
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19170
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19195
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19180
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19339
i_cache_subsystem/i_nbdcache/i_tag_cmp/g18872
i_cache_subsystem/i_nbdcache/master_ports[0].i_cache_ctrl/g23020
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19181
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19190
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19408
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19461
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19442
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19422
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19460
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19432
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19391
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19448
i_cache_subsystem/i_nbdcache/i_tag_cmp/g19414

In [2]:
data_dir = "/home/fetzfs_projects/PlacementCluster/sakundu/PhysicalSynthesis/run_ref"
design = "jpeg_encoder"
cluster_csv = f"{data_dir}/jpeg_encoder_cluster_weight.csv"
hgr_file = f"{data_dir}/{design}_nopin.hgr"

design_obj = Design(design, clusterCsv=cluster_csv)

In [4]:
fp = open(hgr_file, "r")
lines = fp.readlines()
fp.close()

nodMape = {}
node_id = 1
net_count = len(lines)
### Update node count:
for line in lines: 
    items = line.split()
    for item in items[1:]:
        if item not in nodMape.keys():
            nodMape[item] = node_id
            node_id += 1

## output hgr file
hgr_output_file = f"{data_dir}/{design}_nopin_output.hgr"
fp = open(hgr_output_file, "w")
fp.write(f"{net_count} {len(nodMape)}\n")
for line in lines:
    items = line.split()
    for item in items[1:]:
        fp.write(f"{nodMape[item]} ")
    fp.write("\n")
fp.close()

print(f"{hgr_output_file} is generated")

/home/fetzfs_projects/PlacementCluster/sakundu/PhysicalSynthesis/run_ref/jpeg_encoder_nopin_output.hgr is generated

In [3]:
design_obj.read_cluster_csv()

['Cluster_id']
Reading cluster csv for Cluster_id

In [4]:
design_obj.read_hgr_file(hgr_file)

In [6]:
cluster_hgr_file = f"{data_dir}/{design}_cluster.hgr"
netweight_file = f"{data_dir}/{design}_cluster.netweight"
design_obj.create_cluster_hgr_file(cluster_hgr_file)

Info: Net {fdct_dout[0]} is inside a cluster
Info: Net {dfdct_dout[10]} is inside a cluster
Info: Net {dfdct_dout[9]} is inside a cluster
Info: Net {dfdct_dout[8]} is inside a cluster
Info: Net {dfdct_dout[7]} is inside a cluster
Info: Net {dfdct_dout[6]} is inside a cluster
Info: Net {dfdct_dout[5]} is inside a cluster
Info: Net {dfdct_dout[4]} is inside a cluster
Info: Net {dfdct_dout[3]} is inside a cluster
Info: Net {dfdct_dout[2]} is inside a cluster
Info: Net {dfdct_dout[1]} is inside a cluster
Info: Net {dfdct_dout[0]} is inside a cluster
Info: Net {qnr_dout[10]} is inside a cluster
Info: Net {qnr_dout[9]} is inside a cluster
Info: Net {qnr_dout[8]} is inside a cluster
Info: Net {qnr_dout[7]} is inside a cluster
Info: Net {qnr_dout[6]} is inside a cluster
Info: Net {qnr_dout[5]} is inside a cluster
Info: Net {qnr_dout[4]} is inside a cluster
Info: Net {qnr_dout[3]} is inside a cluster
Info: Net {qnr_dout[2]} is inside a cluster
Info: Net {qnr_dout[1]} is inside a cluster
Info: Net {qnr_dout[0]} is inside a cluster
Info: Net dqnr_doe is inside a cluster
Info: Net n_1 is inside a cluster
Info: Net n_2 is inside a cluster
Info: Net n_3 is inside a cluster
Info: Net n_4 is inside a cluster
Info: Net n_5 is inside a cluster
Info: Net n_6 is inside a cluster
Info: Net n_7 is inside a cluster
Info: Net n_8 is inside a cluster
Info: Net n_9 is inside a cluster
Info: Net n_10 is inside a cluster
Info: Net n_11 is inside a cluster
Info: Net n_12 is inside a cluster
Info: Net n_13 is inside a cluster
Info: Net qnr_doe is inside a cluster
Info: Net fdct_zigzag/doe is inside a cluster
Info: Net fdct_zigzag/dct_mod/FE_DBTN189_FE_OCPN791_FE_OFN339_n is inside a cluster
Info: Net fdct_zigzag/dct_mod/FE_DBTN188_FE_OCPN791_FE_OFN339_n is inside a cluster
Info: Net fdct_zigzag/dct_mod/FE_DBTN187_FE_OCPN791_FE_OFN339_n is inside a cluster
Info: Net fdct_zigzag/dct_mod/ddcnt is inside a cluster
Info: Net fdct_zigzag/dct_mod/dddcnt is inside a cluster
Info: Net fdct_zigzag/dct_mod/dgo is inside a cluster
Info: Net fdct_zigzag/dct_mod/go is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_1 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_2 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_3 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_4 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_5 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_6 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_7 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_8 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_9 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_10 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_11 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_12 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_13 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_14 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_15 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_16 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_17 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_18 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_19 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_20 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_21 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_22 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_23 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_24 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_25 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_26 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_27 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_28 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_29 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_30 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_31 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_32 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_33 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_34 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_35 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_36 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_37 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_38 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_45 is inside a cluster
Info: Net fdct_zigzag/dct_mod/n_47 is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/mult_res[18]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/mult_res[14]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/mult_res[13]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/mult_res[12]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/mult_res[11]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/mult_res[10]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/mult_res[9]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/mult_res[8]} is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/FE_DBTN16_n_2 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_2 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_5 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_6 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_7 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_8 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_9 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_10 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_11 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_12 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_13 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_14 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_15 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_16 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_17 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_18 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_19 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_20 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_21 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_22 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_23 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_24 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_25 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_26 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_27 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_28 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_29 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_30 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_31 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_32 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_33 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_34 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_35 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_36 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_37 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_38 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_39 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_40 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_41 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_42 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_43 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_44 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_45 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_46 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_47 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_48 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_49 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_50 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_51 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_52 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_53 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_54 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_55 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_56 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_57 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_58 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_59 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_60 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_61 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_62 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_63 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_64 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_65 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_66 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_67 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_68 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_69 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_70 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_71 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_72 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_73 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_74 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_75 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_76 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_77 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_78 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_79 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_80 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_81 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_82 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_83 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_84 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_85 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_86 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_87 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_88 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_89 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_90 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_91 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_92 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_93 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_94 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_95 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_96 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_97 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_98 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_99 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_100 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/n_101 is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/result[8]_179} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_0/macu/result[9]_180} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/coef[28]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/coef[27]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/coef[26]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/coef[25]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/coef[24]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/coef[23]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/coef[22]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/coef[21]} is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_0 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_2 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_3 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_4 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_5 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_6 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_7 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_8 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_9 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_10 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_11 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_12 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_13 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_14 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_15 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_16 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_17 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_18 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_19 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/n_20 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/FE_DBTN186_mul_100_27_n_83 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/FE_DBTN185_mul_100_27_n_24 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/FE_DBTN184_mul_100_27_n_71 is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[16]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[15]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[14]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[13]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[12]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[11]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[10]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[9]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[8]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[7]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[6]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[5]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[4]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[3]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[2]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[1]} is inside a cluster
Info: Net {fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/mult_res[0]} is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_1 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_2 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_3 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_4 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_5 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_6 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_7 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_8 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_9 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_10 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_11 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_12 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_13 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_14 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_15 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_16 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_17 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_18 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_19 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_20 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_21 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_22 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_23 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_24 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_25 is inside a cluster
Info: Net fdct_zigzag/dct_mod/dct_block_0/dct_unit_1/macu/ADD_UNS_OP_n_26 is inside a cluster

In [ ]:
cluster_df = pd.read_csv(cluster_csv)
test_insts = 'fdct_zigzag/dct_mod/dct_block_7/dct_unit_4/macu/ADD_UNS_OP_g1322'
tmp_df = cluster_df[cluster_df['Name'] == test_insts]
display(tmp_df)

,Name,Type,Master,Height,Width,isSource,isSink,isNode,Cluster_id,color
33649,fdct_zigzag/dct_mod/dct_block_7/dct_unit_4/mac...,inst,C12T32_LL_AOI12X6,1.2,0.544,True,True,True,0,"(50, 50, 50)"

In [11]:
for net in design_obj.nets:
    print(net.name)

In [9]:
print(inst_obj.cluster)

<gen_cluster_lef_def.Cluster object at 0x7f3536097af0>

In [10]:
design_obj.update_cluster_pointer(inst_obj, 1)

In [8]:
net = design_obj.nets[design_obj.netMap['clk']]
print(net.driver.__class__.__name__)

Inst

In [8]:
cluster_df = pd.read_csv(cluster_csv)
test_insts = '{qnr/qnt_cnt_reg[5]}'
inst_id = design_obj.instMap[test_insts]
inst_obj = design_obj.insts[inst_id]
tmp_df = cluster_df[cluster_df['Name'] == test_insts]
display(tmp_df)

,Name,Type,Master,Height,Width,isSource,isSink,isNode,Cluster_id,color
39420,{qnr/qnt_cnt_reg[5]},inst,C12T32_LL_SDFPRQX8,1.2,3.672,True,True,True,47,"(101, 255, 152)"

In [9]:
print(inst_obj.cluster)

<gen_cluster_lef_def.Cluster object at 0x7fa2677e4eb0>

In [1]:
from gen_cluster import *

In [3]:
design = 'mempool_group'
run_dir = f"/home/fetzfs_projects/MacroPlacement/flow_scripts_run/MacroPlacement/Flows/NanGate45/{design}/run/blob_test"
csv_file = f"{run_dir}/{design}_cluster_louvain.csv"
def_file = f"{run_dir}/{design}_cluster_louvain.def"
gen_inst_group_def(csv_file, def_file, design)

In [2]:
design = 'mempool_group'
run_dir = f"/home/fetzfs_projects/MacroPlacement/flow_scripts_run/MacroPlacement/Flows/NanGate45/{design}/run/blob_test"
csv_file = f"{run_dir}/{design}_cluster_leiden.csv"
def_file = f"{run_dir}/{design}_cluster_leiden.def"
gen_inst_group_def(csv_file, def_file, design)

In [2]:
import sys
import os

In [3]:
design = 'aes_cipher_top'
run_dir = f"/home/fetzfs_projects/PlacementCluster/sakundu/PhysicalSynthesis/run_aes/inputs"
def_file = f"{run_dir}/{design}_placed.def"

threshold = 0.005
util = 0.9
output_dir = f"/home/fetzfs_projects/PlacementCluster/sakundu/PhysicalSynthesis/run_aes/outputs/{design}_{threshold}_{util}"

node_file = f"{run_dir}/{design}_nodes.csv"
edge_file = f"{run_dir}/{design}_edges.csv"
input_def = f"{run_dir}/{design}_placed.def"
hgr_file = f"{run_dir}/{design}.hgr"

input_macro_csv = f"{run_dir}/{design}_macro.csv"

cluster_macro = False
if not os.path.exists(input_macro_csv):
    input_macro_csv = None
    cluster_macro = True

input_lef = f"{run_dir}/../28nm_12T.lef"
dbu = 1000
pin_layer = 'M1'

design_db = Design(design, edge_file, node_file, dbu = dbu, cluster_type = 'Leiden', 
              input_def = input_def, hgr_file=hgr_file, input_lef = input_lef,
              output_dir = output_dir, cluster_macro = False,
              macro_csv = input_macro_csv)

Time taken for clustering: 1.0965330600738525 seconds

In [4]:
design_db(threshold, util, pin_layer)

Std cell height:1.2
Time taken to read hgr: 0.18035507202148438
Starting hierarchy clustering

100%|██████████| 45/45 [00:02<00:00, 17.47it/s]

Time taken for hierarchy clustering: 2.5882880687713623
Time taken for removing parallel nets: 0.0436098575592041
Net fanout threshold: 36.1
Net name: clk has fanout 369
Net name: ld has fanout 207
Net name: FE_DBTN1_ld has fanout 113
Net name: FE_DBTN0_ld_r has fanout 110

In [13]:
clk_net = design_db.netMap['clk']
fanout = len(clk_net.sinkCluster)
print(f"{clk_net.name} net fanout: {fanout}")

clk net fanout: 369

In [25]:
fanout_threshold = 0.05*design_db.cluster_count

In [26]:
for net in design_db.nets:
    if net.weight == 0:
        continue
    fanout = len(net.sinkCluster)
    if fanout > fanout_threshold:
        print(f"{net.name} net fanout: {fanout}")

clk net fanout: 369
ld net fanout: 207
FE_DBTN1_ld net fanout: 113
FE_DBTN0_ld_r net fanout: 110

In [2]:
util_list = [0.7, 0.75, 0.8, 0.85, 0.9]
ar_list = [0.8, 0.9, 1, 1.1, 1.2]

run_script = '/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh'
design = 'ariane'
run_dir = f'/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/{design}'
threshold = 0.1
net_threshold = 0.1

for util in util_list:
    for ar in ar_list:
        print(f"{run_script} {threshold} {util} {run_dir} {design} {net_threshold} {ar}")

/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.7 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 0.8
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.7 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 0.9
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.7 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.7 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1.1
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.7 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1.2
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.75 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 0.8
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.75 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 0.9
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.75 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.75 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1.1
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.75 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1.2
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.8 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 0.8
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.8 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 0.9
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.8 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.8 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1.1
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.8 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1.2
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.85 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 0.8
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.85 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 0.9
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.85 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.85 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1.1
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.85 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1.2
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.9 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 0.8
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.9 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 0.9
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.9 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.9 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1.1
/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/Scripts/run_cluster_placement_invs_flow.sh 0.1 0.9 /home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/flows/inputs/blob_inputs/ariane ariane 0.1 1.2

In [4]:
line = 'ariane_0.1_0.7_0.8_0.1_164742_11062023/innovus_run/ariane_DETAILS.rpt:postRouteOpt,1814274.28,248591.364,1018355.73,840.58617611,5147865.06999,-0.172,-122.110,,'
rpt = '/home/fetzfs_projects/PlacementCluster/sakundu/BlobPlacement/blob_runs/ariane_sweep_util_sweep_details'
fp = open(rpt, "r")
lines = fp.readlines()
fp.close()

for line in lines:
    items = line.split(',')
    util = items[0].split('_')[2]
    ar = items[0].split('_')[3]
    power = items[4]
    rwl = items[5]
    wns = items[6]
    tns = items[7]
    print(f"{util},{ar},{rwl},{power},{wns},{tns}")

0.7,0.8,5147865.06999,840.58617611,-0.172,-122.110
0.7,0.9,5141058.49999,836.89585172,-0.104,-72.055
0.7,1,5134248.98499,839.11525744,-0.124,-124.882
0.7,1.1,5129270.90499,840.52358076,-0.156,-98.353
0.7,1.2,5105511.74999,842.18516761,-0.089,-67.766
0.75,0.75,5036378.93498,839.94477965,-0.119,-67.748
0.75,0.8,4989739.52999,838.48122532,-0.153,-105.601
0.75,0.9,5004589.52999,838.56973156,-0.099,-46.992
0.75,1,5005291.89498,833.96974359,-0.087,-42.879
0.75,1.1,5036805.91498,838.13396935,-0.168,-65.158
0.75,1.2,4993105.64998,837.92366886,-0.096,-56.591
0.8,0.75,5001625.50499,838.37865243,-0.083,-54.358
0.8,0.8,5022732.14499,837.86929097,-0.119,-62.846
0.8,0.9,5062112.31999,838.92841403,-0.066,-26.383
0.8,1,5153753.23999,843.32894204,-0.103,-91.453
0.8,1,5023317.42999,835.61304360,-0.125,-87.156
0.8,1.1,5016394.82999,839.79385809,-0.083,-58.880
0.8,1.2,5009275.84499,837.82651342,-0.130,-96.531
0.85,0.8,5083499.24499,836.43908637,-0.069,-25.967
0.85,0.9,5069984.50999,838.16120949,-0.086,-44.050
0.85,1,5060817.32498,836.62970047,-0.081,-25.952
0.85,1.1,5115093.28498,838.30263018,-0.113,-80.769
0.85,1.2,5090757.27498,837.27654278,-0.087,-32.496
0.9,0.8,5043275.30499,838.38960737,-0.141,-76.863
0.9,0.9,5120709.58499,837.53907551,-0.100,-33.939
0.9,1,5111136.87499,838.80868350,-0.087,-43.327
0.9,1.1,5082027.47998,839.38742340,-0.059,-15.238
0.9,1.2,5081821.39499,839.03024436,-0.121,-66.940

In [63]:
config_file_dir = "/home/fetzfs_projects/OpenROAD/sakundu/OpenROAD-flow-scripts/flow/blob_inputs"
config_file_list = [f"{config_file_dir}/aes_config.mk", f"{config_file_dir}/jpeg_config.mk", f"{config_file_dir}/megaboom_config.mk"]
config_file_list = [f"{config_file_dir}/jpeg_config.mk"]
utillization = [75, 80, 85, 90]
gp_padding = [0, 1]
dp_padding = [0]
enable_dpo = [0, 1]
job_file = "/home/fetzfs_projects/OpenROAD/sakundu/OpenROAD-flow-scripts/flow/blob_inputs/jobs/job_list_jpeg"

fp = open(job_file, "w")
for config_file in config_file_list:
    for util in utillization:
        for gp in gp_padding:
            for dp in dp_padding:
                for dpo in enable_dpo:
                    flow_variant = f"UTIL_{util}_GP_{gp}_DP_{dp}_DPO_{dpo}"
                    args = f"CELL_PAD_IN_SITES_GLOBAL_PLACEMENT={gp}"
                    args = f"{args} CELL_PAD_IN_SITES_DETAIL_PLACEMENT={dp}"
                    args = f"{args} ENABLE_DPO={dpo}"
                    args = f"{args} CORE_UTILIZATION={util}"
                    args = f"{args} FLOW_VARIANT={flow_variant}"
                    fp.write(f"make report DESIGN_CONFIG={config_file} {args}\n")
fp.close()

In [9]:
hwpl_gp = 401570884*1.0 / 2000
hpwl_gp1 = 202153.4

print(f"{hwpl_gp} {hpwl_gp1}")

200785.442 202153.4

In [54]:
def get_run_config(log_dir:str) -> List[str]:
    base_dir = os.path.basename(log_dir)
    items = base_dir.split('_')
    util = items[1]
    gp_pad = items[3]
    dp_pad = items[5]
    dpo = items[7]
    return [util, gp_pad, dp_pad, dpo]

def convert_runtime_string_to_second(runtime_string:str) -> float:
    items = runtime_string.split(':')
    if len(items) > 3:
        print(f"Error: {runtime_string}")
        return -1.0
    
    if len(items) == 3:
        hours = int(items[0])
        minutes = int(items[1])
        seconds = float(items[2])
        return hours*3600 + minutes*60 + seconds
    elif len(items) == 2:
        minutes = int(items[0])
        seconds = float(items[1])
        return minutes*60 + seconds
    
    return float(items[0])
    

def get_gplace_details(log_dir:str) -> List[float]:
    gplace_log = f"{log_dir}/3_3_place_gp.log"
    dbu = 1000
    hpwl = -1.0
    run_time = -1.0
    if not os.path.exists(gplace_log):
        return [hpwl, run_time]
    fp = open(gplace_log, "r")
    lines = fp.readlines()
    fp.close()
    for line in lines:
        items = line.split()
        if len(items) == 4 and items[2] == 'DBU:':
            dbu = int(items[3])
        elif len(items) == 7 and items[0] == '[NesterovSolve]':
            hpwl = float(items[6])/dbu
        
    if lines[-1].startswith('Elapsed time'):
        runtime_string = lines[-1].split()[2]
        # Find runtime from this format: 0:47.58[h:]min:sec
        # Find the first match of a regex
        time_string = re.search(r"^([0-9:.]+)", runtime_string).group(1)
        run_time = convert_runtime_string_to_second(time_string)
    return [hpwl, run_time]

def get_dplace_details(log_dir:str) -> List[float]:
    dp_log = f"{log_dir}/3_5_place_dp.log"
    dp_hpwl = -1.0
    dp_runtime = -1.0
    if not os.path.exists(dp_log):
        return [dp_hpwl, dp_runtime]
    fp = open(dp_log, "r")
    lines = fp.readlines()
    fp.close()
    
    for line in lines:
        if re.search(" HPWL after", line):
            items = line.split()
            dp_hpwl = float(items[4])
        elif line.startswith('Elapsed time'):
            runtime_string = line.split()[2]
            time_string = re.search(r"^([0-9:.]+)", runtime_string).group(1)
            dp_runtime = convert_runtime_string_to_second(time_string)
    return [dp_hpwl, dp_runtime]

def get_route_report(log_dir:str) -> List[float]:
    route_log = f"{log_dir}/5_3_route.log"
    rwl = -1.0
    runtime = -1.0
    if not os.path.exists(route_log):
        return [rwl, runtime]
    fp = open(route_log, "r")
    lines = fp.readlines()
    fp.close()
    for line in lines:
        if line.startswith('Total wire length ='):
            items = line.split()
            rwl = float(items[4])
        elif line.startswith('Elapsed time'):
            runtime_string = line.split()[2]
            time_string = re.search(r"^([0-9:.]+)", runtime_string).group(1)
            runtime = convert_runtime_string_to_second(time_string)
    return [rwl, runtime]

def report_final_ppa(log_dir:str) -> List[float]:
    report_log = f"{log_dir}/6_report.log"
    wns =  float('-inf')
    tns =  float('-inf')
    power = -1.0
    if not os.path.exists(report_log):
        return [wns, tns, power]
    fp = open(report_log, "r")
    lines = fp.readlines()
    fp.close()
    
    for line in lines:
        if line.startswith('wns'):
            items = line.split()
            wns = float(items[1])
        elif line.startswith('tns'):
            items = line.split()
            tns = float(items[1])
        elif line.startswith('Total'):
            items = line.split()
            power = float(items[-2])
    return [wns, tns, power]

def extract_report(log_dir:str) -> None:
    [util, gp_pad, dp_pad, dpo] = get_run_config(log_dir)
    [hpwl, gp_runtime] = get_gplace_details(log_dir)
    [dp_hpwl, dp_runtime] = get_dplace_details(log_dir)
    [rwl, route_runtime] = get_route_report(log_dir)
    [wns, tns, power] = report_final_ppa(log_dir)
    print(f"{util},{gp_pad},{dp_pad},{dpo},{hpwl},{gp_runtime},{dp_hpwl},{dp_runtime},{rwl},{route_runtime},{wns},{tns},{power}")

def extract_report_all(log_dir:str) -> None:
    print("Util,GP_PAD,DP_PAD,DPO,GP_HPWL,GP_RUNTIME,DP_HPWL,DP_RUNTIME,RWL,ROUTE_RUNTIME,WNS,TNS,POWER")
    for sub_dir in os.listdir(log_dir):
        if sub_dir.startswith('UTIL'):
            extract_report(f"{log_dir}/{sub_dir}")

In [60]:
log_dir = '/home/fetzfs_projects/OpenROAD/sakundu/OpenROAD-flow-scripts/flow/logs/nangate45/jpeg'
extract_report_all(log_dir)

Util,GP_PAD,DP_PAD,DPO,GP_HPWL,GP_RUNTIME,DP_HPWL,DP_RUNTIME,RWL,ROUTE_RUNTIME,WNS,TNS,POWER
30,1,1,0,375214.442,153.66,444554.2,16.44,568129.0,267.67,-0.21,-71.67,0.403
50,0,0,1,309767.458,148.07,352662.9,42.3,464478.0,493.11,-0.15,-38.01,0.402
70,0,1,1,280771.1055,157.0,-1.0,-1.0,-1.0,-1.0,-inf,-inf,-1.0
35,1,0,1,363612.46,181.28,389108.7,51.17,518278.0,376.67,-0.2,-57.22,0.404
55,0,1,0,306869.792,177.2,1725822.9,39.22,-1.0,-1.0,-inf,-inf,-1.0
40,0,0,1,319122.7515,178.57999999999998,359851.8,47.37,465964.0,438.44,-0.21,-58.8,0.401
20,1,1,0,388909.8015,157.8,458704.5,18.64,588260.0,288.7,-0.21,-59.86,0.404
65,0,0,0,298994.0835,140.12,367767.5,16.04,488808.0,469.36,-0.17,-46.69,0.405
60,0,1,1,303921.6155,146.91,-1.0,-1.0,-1.0,-1.0,-inf,-inf,-1.0
45,0,1,0,313263.736,181.86,1038701.9,27.39,-1.0,-1.0,-inf,-inf,-1.0
25,1,0,1,383146.195,183.27,408805.6,49.25,531358.0,379.87,-0.14,-36.76,0.404
50,0,1,1,309767.458,209.88,1152314.2,57.46,-1.0,-1.0,-inf,-inf,-1.0
30,1,0,0,375214.442,150.04,422071.1,16.94,548134.0,267.76,-0.23,-64.08,0.403
55,0,0,0,306869.792,140.16,369194.5,16.08,483614.0,381.12,-0.17,-52.48,0.402
35,1,1,1,363612.46,157.54,414952.8,58.71,544674.0,307.21,-0.22,-54.02,0.406
70,0,0,1,280771.1055,131.67,356106.2,42.22,465310.0,450.86,-0.14,-38.22,0.396
65,0,1,0,298994.0835,171.92000000000002,-1.0,-1.0,-1.0,-1.0,-inf,-inf,-1.0
20,1,0,0,388909.8015,186.35,437509.1,26.48,568401.0,348.03,-0.21,-58.71,0.406
40,0,1,1,319122.7515,140.26,694949.0,44.11,1105170.0,436.42,-0.15,-40.19,0.403
25,1,1,1,383146.195,147.47,431886.5,45.77,556067.0,187.36,-0.14,-35.24,0.404
45,0,0,0,313263.736,151.73,376493.9,21.76,493156.0,512.13,-0.13,-38.38,0.403
60,0,0,1,303921.6155,173.96,347283.4,51.77,458908.0,416.75,-0.14,-41.75,0.4
45,1,1,1,356326.9905,147.31,414250.9,31.43,538967.0,283.12,-0.18,-61.68,0.407
25,0,0,0,335282.278,187.64,396826.1,21.37,519175.0,442.05,-0.17,-41.43,0.403
60,1,1,0,319163.0755,142.61,512395.5,16.89,768685.0,306.31,-0.21,-44.45,0.402
65,1,0,1,315499.3225,133.85,366241.7,43.08,475295.0,328.1,-0.13,-36.79,0.404
40,1,0,0,364570.5065,155.15,410694.7,21.72,532594.0,331.66,-0.21,-52.65,0.401
20,0,1,1,339622.685,194.56,422803.1,50.38,546752.0,324.75,-0.2,-36.29,0.401
35,0,0,0,321116.1235,179.04,382044.9,20.29,498642.0,403.29,-0.18,-62.62,0.404
55,1,1,1,323697.6265,153.04,420389.8,43.86,563857.0,221.12,-0.19,-43.91,0.402
70,1,1,0,311628.2505,163.91,-1.0,-1.0,-1.0,-1.0,-inf,-inf,-1.0
30,0,1,1,327060.2895,181.85,449557.7,51.13,586595.0,328.91,-0.11,-25.71,0.399
50,1,0,0,330223.66,140.11,403431.2,16.85,522148.0,337.33,-0.21,-51.38,0.405
60,1,0,0,319163.0755,162.71,393917.3,19.5,503069.0,429.16,-0.16,-38.69,0.399
25,0,1,0,335282.278,147.3,468561.6,17.28,624590.0,292.42,-0.22,-42.63,0.405
45,1,0,1,356326.9905,148.93,383223.6,43.19,498880.0,429.27,-0.23,-48.47,0.406
20,0,0,1,339622.685,166.1,378823.2,46.3,490735.0,434.37,-0.15,-29.1,0.399
40,1,1,0,364570.5065,183.32,436699.6,21.52,551670.0,275.38,-0.2,-36.56,0.397
65,1,1,1,315499.3225,136.74,768137.8,50.49,-1.0,-1.0,-inf,-inf,-1.0
70,1,0,0,311628.2505,160.2,388380.0,19.34,499124.0,425.65,-0.19,-41.44,0.398
55,1,0,1,323697.6265,144.95,371374.0,40.73,482609.0,350.46,-0.19,-45.61,0.404
35,0,1,0,321116.1235,149.6,583907.5,20.54,799350.0,447.6,-0.21,-59.29,0.402
50,1,1,0,330223.66,137.88,454253.2,16.57,584618.0,263.0,-0.23,-48.85,0.403
30,0,0,1,327060.2895,147.86,368781.0,43.72,478437.0,402.24,-0.14,-38.96,0.401
20,1,0,1,388909.8015,150.15,414504.7,38.42,539866.0,298.53,-0.23,-75.03,0.406
40,0,1,0,319122.7515,177.54,795749.1,23.4,-1.0,-1.0,-inf,-inf,-1.0
65,0,1,1,298994.0835,172.98,-1.0,-1.0,-1.0,-1.0,-inf,-inf,-1.0
60,0,0,0,303921.6155,136.14,367306.6,17.08,483128.0,414.27,-0.19,-43.67,0.403
25,1,1,0,383146.195,184.03,452257.0,26.01,576988.0,254.51,-0.15,-39.1,0.406
45,0,0,1,313263.736,148.12,356028.1,42.87,473335.0,529.77,-0.25,-46.36,0.408
50,0,1,0,309767.458,171.85,1312433.2,24.68,-1.0,-1.0,-inf,-inf,-1.0
30,1,0,1,375214.442,155.4,400582.2,44.74,526894.0,403.1,-0.14,-43.4,0.407
70,0,0,0,280771.1055,130.89,392141.8,17.74,514516.0,638.46,-0.15,-35.99,0.4
55,0,0,1,306869.792,201.4,349084.2,50.73,463442.0,444.83,-0.2,-59.38,0.403
35,1,1,0,363612.46,148.94,433829.5,22.31,564362.0,228.75,-0.2,-49.5,0.406
65,0,0,1,298994.0835,141.57,347788.0,31.68,468469.0,401.56,-0.18,-44.03,0.406
40,0,0,0,319122.7515,144.4,380775.4,16.74,490141.0,492.36,-0.19,-49.72,0.399
20,1,1,1,388909.8015,152.44,436735.3,42.28,567332.0,240.94,-0.19,-52.7,0.412
45,0,1,1,313263.736,181.88,905525.4,65.66,-1.0,-1.0,-inf,-inf,-1.0
25,1,0,0,383146.195,150.42000000000002,430805.7,16.61,551021.0,331.44,-0.14,-33.08,0.399
60,0,1,0,303921.6155,144.52,-1.0,-1.0,-1.0,-1.0,-inf,-inf,-1.0
30,1,1,1,375214.442,182.58,424517.0,48.69,552751.0,231.77,-0.23,-53.37,0.407
50,0,0,0,309767.458,155.01,373029.0,23.64,488365.0,580.65,-0.18,-56.61,0.402
35,1,0,0,363612.46,183.61,409681.3,20.29,541323.0,359.46,-0.21,-49.82,0.408
55,0,1,1,306869.792,143.95,1549507.4,62.36,-1.0,-1.0,-inf,-inf,-1.0
70,0,1,0,280771.1055,131.02,-1.0,-1.0,-1.0,-1.0,-inf,-inf,-1.0
55,1,0,0,323697.6265,132.96,396643.8,16.17,508391.0,355.95,-0.18,-37.61,0.401
35,0,1,1,321116.1235,146.64,505939.5,44.38,660079.0,367.4,-0.21,-56.81,0.398
70,1,0,1,311628.2505,137.53,362528.6,40.53,471505.0,328.88,-0.19,-43.47,0.404
50,1,1,1,330223.66,175.34,419160.3,42.51,547782.0,259.38,-0.17,-41.11,0.401
30,0,0,0,327060.2895,154.07,390942.2,23.11,508487.0,480.88,-0.16,-42.47,0.404
25,0,1,1,335282.278,155.27,427287.6,48.25,577834.0,393.6,-0.18,-43.13,0.406
45,1,0,0,356326.9905,150.37,402448.3,18.22,522320.0,387.66,-0.22,-50.91,0.404
60,1,0,1,319163.0755,164.81,368160.6,46.21,474869.0,403.02,-0.14,-41.28,0.4
65,1,1,0,315499.3225,132.19,866203.9,19.14,-1.0,-1.0,-inf,-inf,-1.0
20,0,0,0,339622.685,158.87,403390.0,21.85,517824.0,350.64,-0.17,-39.14,0.4
40,1,1,1,364570.5065,180.27,419704.6,38.12,536685.0,268.11,-0.18,-49.06,0.399
70,1,1,1,311628.2505,133.05,-1.0,-1.0,-1.0,-1.0,-inf,-inf,-1.0
35,0,0,1,321116.1235,142.4,360464.7,41.49,470059.0,323.36,-0.19,-49.27,0.398
55,1,1,0,323697.6265,165.49,461184.3,20.78,610364.0,299.92,-0.18,-41.64,0.403
30,0,1,0,327060.2895,181.36,505716.8,20.72,690523.0,400.27,-0.16,-35.63,0.403
50,1,0,1,330223.66,201.12,377564.6,42.85,486192.0,370.86,-0.22,-46.07,0.397
60,1,1,1,319163.0755,134.8,450574.5,42.04,616951.0,270.01,-0.18,-38.09,0.4
45,1,1,0,356326.9905,151.34,432067.5,17.27,559308.0,347.45,-0.16,-46.95,0.407
25,0,0,1,335282.278,184.2,373721.8,58.05,492793.0,429.42,-0.19,-38.3,0.406
40,1,0,1,364570.5065,148.04,390667.9,41.53,503613.0,384.6,-0.19,-55.69,0.4
20,0,1,0,339622.685,159.06,458404.4,16.95,596335.0,326.77,-0.15,-34.89,0.406
65,1,0,0,315499.3225,158.64,391263.8,19.79,503099.0,421.07,-0.14,-34.99,0.401

In [59]:
log_dir = '/home/fetzfs_projects/OpenROAD/sakundu/OpenROAD-flow-scripts/flow/logs/nangate45/aes/UTIL_65_GP_1_DP_0_DPO_1'
run_config = get_run_config(log_dir)
gp_result = get_gplace_details(log_dir)
print(run_config, gp_result)
extract_report(log_dir)

['65', '1', '0', '1'] [171662.3635, 48.16]
65,1,0,1,171662.3635,48.16,173382.3,12.54,254447.0,1137.62,-0.2,-29.1,0.28

In [44]:
from typing import List, Dict, Tuple, Set, Optional, IO
import re
import os

def add_tie_lo(net:str, tie_lo_id:int, fp:IO) -> None:
    net_name = f"lo_net_{tie_lo_id}"
    ## Add the new wire
    fp.write(f"  wire {net_name};\n")
    ## Add the tie_lo cell
    fp.write(f"  LOGIC0_X1 lo_{tie_lo_id} ( .Z({net_name}) );\n")
    ## Add the buffer
    fp.write(f"  BUF_X1 lo_buf_{tie_lo_id} ( .A({net_name}), .Z({net}) );\n")
    return

def add_tie_hi(net:str, tie_hi_id:int, fp:IO) -> None:
    net_name = f"hi_net_{tie_hi_id}"
    ## Add the new wire
    fp.write(f"  wire {net_name};\n")
    ## Add the tie_lo cell
    fp.write(f"  LOGIC1_X1 hi_{tie_hi_id} ( .Z({net_name}) );\n")
    ## Add the buffer
    fp.write(f"  BUF_X1 hi_buf_{tie_hi_id} ( .A({net_name}), .Z({net}) );\n")
    return

def add_tie_hi_lo(input_netlist:str, output_netlist:str) -> None:
    ## Read the line one by one instead of loading the  whole file
    fp = open(output_netlist, "w")
    tie_lo_id = 0
    tie_hi_id = 0
    with open(input_netlist, 'r') as f:
        for line in f:
            if line.startswith('  assign'):
                items = line.strip().split()
                net = items[1]
                if items[-1] == '1\'b0;':
                    add_tie_lo(net, tie_lo_id, fp)
                    tie_lo_id += 1
                elif items[-1] == '1\'b1;':
                    add_tie_hi(net, tie_hi_id, fp)
                    tie_hi_id += 1
                else:
                    print(f"Error: {line}")
                    fp.write(line)
            elif re.search("1'b1", line):
                fp.write(f"  wire hi_net_{tie_hi_id}, hi_net_buf_{tie_hi_id};\n")
                fp.write(f"  LOGIC1_X1 hi_{tie_hi_id} ( .Z(hi_net_{tie_hi_id}) );\n")
                fp.write(f"  BUF_X1 hi_buf_{tie_hi_id} ( .A(hi_net_{tie_hi_id}), .Z(hi_net_buf_{tie_hi_id}) );\n")
                line = line.replace("1'b1", f"hi_net_buf_{tie_hi_id}")
                fp.write(line)
                tie_hi_id += 1
            elif re.search("1'b0", line):
                fp.write(f"  wire hi_net_{tie_lo_id}, hi_net_buf_{tie_lo_id};\n")
                fp.write(f"  LOGIC1_X1 hi_{tie_lo_id} ( .Z(hi_net_{tie_lo_id}) );\n")
                fp.write(f"  BUF_X1 hi_buf_{tie_lo_id} ( .A(hi_net_{tie_lo_id}), .Z(hi_net_buf_{tie_lo_id}) );\n")
                line = line.replace("1'b1", f"hi_net_buf_{tie_lo_id}")
                fp.write(line)
                tie_lo_id += 1
            else:
                fp.write(line)
    fp.close()


input_netlist = '/home/fetzfs_projects/OpenROAD/sakundu/OpenROAD-flow-scripts/flow/blob_inputs/netlist/jpeg_encoder_bkp.v'
output_netlist = '/home/fetzfs_projects/OpenROAD/sakundu/OpenROAD-flow-scripts/flow/blob_inputs/netlist/jpeg_encoder.v'
add_tie_hi_lo(input_netlist, output_netlist)

In [43]:
line = "  SDFFR_X2 \mult_res_reg[17] (.RN (1'b1), .CK (clk), .D (n_51), .SE"
a = re.search("1'b1", line)
# line = line.replace("1'b1", "test")
# print(line)

if re.search("1'b1", line):
    print("Found")

Found

In [33]:
line = "assign io_debug_resp_bits_resp[1] = 1'b1;"
tie_hi = False
tie_low = False
tie_lo_id = 0
tie_hi_id = 0
if line.startswith("assign"):
    ## Check is it tie high or tie low
    items = line.split()
    net = items[1]
    if items[-1] == '1\'b0;':
        add_tie_lo(net, tie_lo_id)
    elif items[-1] == '1\'b1;':
        add_tie_hi(net, tie_hi_id)

  wire hi_net_0;
  LOGIC1_X1 hi_0 ( .Z(hi_net_0) );
  BUFF_X1 hi_buf_0 ( .A(hi_net_0), .Z(io_debug_resp_bits_resp[1]) );

In [14]:
import re

temp_string = "0:47.58[h:]min:sec"
time_string = re.search(r"^([0-9:.]+)", temp_string).group(1)
print(time_string)

0:47.58

In [1]:
import os
run_dir = '/home/fetzfs_projects/Tomography/sakundu/kth_sweep_ml_data'
job_file = f'{run_dir}/d3yoon/train_job_file'
new_job_file = f'{run_dir}/sk_missing_asap7_job_file'

fp = open(new_job_file, "w")
with open(job_file, 'r') as f:
    for line in f:
        items = line.split()
        job_details = items[3]
        run_type = job_details.split('_')[0]
        run_id = int(job_details.split('_')[1])
        sub_id = int(run_id/100)
        drc_file = f"{run_dir}/{run_type}_asap7/run_sub_{sub_id}/run_{run_id}/post_eco_fix_drc.rpt"
        if not os.path.exists(drc_file):
            fp.write(line)
        
        # fp.write(line)
fp.close()